name: IQA-serverless-document-parser

on:
  push:
    branches: [iqa]
    paths:
      - 'docling/**'
jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      docling: ${{ steps.filter.outputs.docling }}
      marker: ${{ steps.filter.outputs.marker }}

    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ github.ref }}
          filters: |
            docling:
              - 'docling/**'

  build-and-deploy-docling:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.docling == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Connection
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if it doesn't exist
        env:
          REPOSITORY: ${{ github.event.repository.name }}
        run: |
          aws ecr describe-repositories --repository-names $REPOSITORY --region ${{ secrets.AWS_REGION }} || \
          aws ecr create-repository --repository-name $REPOSITORY --region ${{ secrets.AWS_REGION }}

      - name: Build and push Docling Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ github.event.repository.name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --platform linux/amd64 --provenance=false -f docling/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest

